<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $user = [
            [ 
                'last_name' => null,
                'name' => 'Admin',
                'middle_name' => null,
                'sex_id' => 1,
                'date_birth' => null,
                'birth_place' => null,
                'home_address' => null,
                'mobile_number' => null,
                'land_line_no' => null,
                'civil_status_id' => null,
                'email' => 'admin@gmail.com',
                'facebook_account' => 'admin@yahoo.com',
                'year_graduate' => null,
                'educational_level_id' => null,
                'graduate_school_campus' => null,
                'course_id' => null,
                'major_in' => 'None',
                'employment_status_id' => null,
                'present_occupation' => null,
                'type_work_id' => null,
                'name_of_company' => null,
                'employment_address' => null,
                'reference_person_workplace' => null,
                'reference_person_workplace_contact_no' => null,
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => null,
                'password' => bcrypt('admin123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 1,
            ],
            [ 
                'last_name' => 'User',
                'name' => 'User',
                'middle_name' => 'User',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni@gmail.com',
                'facebook_account' => 'alumni@yahoo.com',
                'year_graduate' => '2023',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 1,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
            [ 
                'last_name' => 'User2',
                'name' => 'User2',
                'middle_name' => 'User2',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni1@gmail.com',
                'facebook_account' => 'alumni1@yahoo.com',
                'year_graduate' => '2023',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 1,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
            [ 
                'last_name' => 'User3',
                'name' => 'User3',
                'middle_name' => 'User3',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni2@gmail.com',
                'facebook_account' => 'alumni2@yahoo.com',
                'year_graduate' => '2023',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 1,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
            [ 
                'last_name' => 'User4',
                'name' => 'User4',
                'middle_name' => 'User4',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni3@gmail.com',
                'facebook_account' => 'alumni3@yahoo.com',
                'year_graduate' => '2023',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 1,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
            [ 
                'last_name' => 'User5',
                'name' => 'User5',
                'middle_name' => 'User5',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni4@gmail.com',
                'facebook_account' => 'alumni4@yahoo.com',
                'year_graduate' => '2010',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 1,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
            [ 
                'last_name' => 'User6',
                'name' => 'User6',
                'middle_name' => 'User6',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni5@gmail.com',
                'facebook_account' => 'alumni5@yahoo.com',
                'year_graduate' => '2022',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 1,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
            [ 
                'last_name' => 'User7',
                'name' => 'User7',
                'middle_name' => 'User7',
                'sex_id' => 1,
                'date_birth' => '1999-09-10',
                'birth_place' => 'Dumaguete City',
                'home_address' => 'Dumaguete City',
                'mobile_number' => '09212969669',
                'land_line_no' => '',
                'civil_status_id' => 1,
                'email' => 'alumni6@gmail.com',
                'facebook_account' => 'alumni6@yahoo.com',
                'year_graduate' => '2010',
                'educational_level_id' => 1,
                'graduate_school_campus' => 'NORSU MAIN',
                'course_id' => 1,
                'major_in' => 'None',
                'employment_status_id' => 2,
                'present_occupation' => 'Faculty',
                'type_work_id' => 1,
                'name_of_company' => 'NORSU',
                'employment_address' => 'Dumaguete',
                'reference_person_workplace' => 'Roche',
                'reference_person_workplace_contact_no' => '09212969669',
                'person_to_notify' => 'Jovita',
                'person_to_notify_contact_no' => '09212969669',
                'password' => bcrypt('alumni123'),
                'email_verified_at' => '2024-05-24 11:16:16',
                'role_id' => 2,
            ],
        ];

        User::insert($user);
    }
}
